#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 13 10:33:33 CEST 2021
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim PGCD_tb_behav -key {Behavioral:sim_1:Functional:PGCD_tb} -tclbatch PGCD_tb.tcl -view /net/e/fpouget001/SE/EN325-Advanced-digital-design/Partie-1/2_Hardware/Etape_1/vivado/PGCD/PGCD_tb_behav.wcfg -log simulate.log
